version: '3.8'

services:
  chatterbox-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEVICE=cuda  # GPU is required
      - MODEL_CACHE_DIR=/app/models
      - LOG_LEVEL=info
    volumes:
      - ./models:/app/models  # Persist model cache between restarts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s