services:
  chatterbox-api:
    build: .
    ports:
      - "8308:8308"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PORT=8308
      - HOST=0.0.0.0
      - DEVICE=cuda
      - MODEL_CACHE_DIR=/app/models
      - LOG_LEVEL=info
    volumes:
      - .:/app
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8308/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s